version: '0.1'

services:
  postgre_db:
    container_name: postgre_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:16.0-alpine3.18
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: Zhigurov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: passadm
    ports:
      - "5050:80"
